# Binomial Distributions
Use NumPy to create simulations and compute proportions for the following outcomes. The first one is done for you.

In this quiz, you will simulate coin flips using np.random.binomial to compute proportions for the following outcomes.

* A fair coin flip produces heads
* Five fair coin flips produce exactly one head
* Ten fair coin flips produce exactly four heads
* Five biased coin flips with P(H) = 0.8 produce exactly five heads
* Ten biased coin flips with P(H) = 0.15 produce at least three heads

Then, you'll compare these proportions with probabilities in the quizzes below.

In [1]:
# import numpy
import numpy as np

### 1. A fair coin flip produces heads

In [2]:
# simulate 1 million tests of one fair coin flip
# remember, the output of these tests are the # successes, or # heads
n = np.random.binomial(1,.5 ,10**6)
print(n)
# proportion of tests that produced heads
n.mean()

[0 0 0 ... 0 0 0]


0.499808

### 2. Five fair coin flips produce exactly one head

In [3]:
# simulate 1 million tests of five fair coin flips
n = np.random.binomial(5 ,.5,10**6)
print(n)
print((np.sum(n == 4)))

# proportion of tests that produced 1 head
(n==1).mean()


[3 5 4 ... 2 2 2]
156111


0.156569

### 3. Ten fair coin flips produce exactly four heads

In [4]:
# simulate 1 million tests of ten fair coin flips
n = np.random.binomial(10,.5,10**6)
print(n)
print(np.sum(n == 4))

# proportion of tests that produced 4 heads
(n==4).mean()

[5 5 6 ... 7 7 3]
205298


0.205298

### 4. Five biased coin flips with P(H) = 0.8 produce exactly five heads

In [5]:
# simulate 1 million tests of five biased coin flips
n = np.random.binomial(5,.8,10**6)
print(n)
print(np.sum(n == 5))

# proportion of tests that produced 5 heads
(n==5).mean()

[4 4 3 ... 5 3 4]
327544


0.327544

### 5. Ten biased coin flips with P(H) = 0.15 produce at least 3 heads

In [6]:
# simulate 1 million tests of ten biased coin flips
n = np.random.binomial(10,.15,10**6)
print(n)
print(np.sum(n == 3))

# proportion of tests that produced at least 3 heads
(n==3).mean()

[1 3 2 ... 2 2 1]
129865


0.129865