# Coin Flips and Die Rolls
Use NumPy to create simulations and compute proportions for the following outcomes. The first one is done for you.

**Please note again that we are using 0 to represent heads, and 1 to represent tails.**

### In this quiz, you will simulate coin flips and die rolls to compute proportions for the following outcomes.
* Two fair coin flips produce exactly two heads.
* Three fair coin flips produce exactly one head.
* Three biased coin flips with P(H) = 0.6 produce exactly one head.
* A die rolls an even number.
* Two dice roll a double.

Then, you'll compare these proportions with probabilities in the quizzes below.

When simulating coin flips, use 0 to represent heads and 1 to represent tails. When simulating die rolls, use the correct integers to match the numbers on the sides of a standard 6 sided die.

Also, notice that you can look at the solutions if you get stuck by clicking the orange button in the top left or check the solution link at the bottom of the page.


In [1]:
# import numpy
import numpy as np

### 1. Two fair coin flips produce exactly two heads

In [2]:
# simulate 1 million tests of two fair coin flips
n = np.random.randint(2,size = (10**6,2))

# sums of all tests
sumn = n.sum(axis=1)


print(sumn)
# proportion of tests that produced exactly two heads
(sumn == 0).mean()

[1 1 0 ... 1 0 1]


0.250239

### 2. Three fair coin flips produce exactly one head

In [3]:
# simulate 1 million tests of three fair coin flips
n = np.random.randint(2 , size = (10**6,3))

# sums of all tests
sumn = n.sum(axis=1)
print(sumn)
# proportion of tests that produced exactly one head
(sumn == 1).mean()

[2 1 2 ... 0 2 2]


0.374369

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [4]:
# simulate 1 million tests of three biased coin flips
# hint: use np.random.choice()
n = np.random.choice([0,1],size = [10**6 ,3],p=[.6,.4])

# sums of all tests
sums = n.sum(axis =1)
print(sums)
# proportion of tests that produced exactly one head
(sums == 2).mean()

[3 2 1 ... 0 1 3]


0.288361

### 4. A die rolls an even number

In [5]:
# simulate 1 million tests of one die roll
n = np.random.randint(1,7,size = 10**6)
# proportion of tests that produced an even number
(n %2 ==0).mean()

0.500014

### 5. Two dice roll a double

In [6]:
# simulate the first million die rolls
n = np.random.randint(1,7,size =(10**6))
print(n)
# simulate the second million die rolls
n1 = np.random.randint(1,7,size = (10**6))
print(n1)
# proportion of tests where the 1st and 2nd die rolled the same number
(n == n1).mean()

[3 2 3 ... 4 3 4]
[3 1 5 ... 1 3 3]


0.16695